### ISSUE TITLE
[2024-02] EVERYONE: Review Section 1: Overview

### ISSUE THREAD

**Issue by benjie** [graphql/composite-schemas-wg#128]
Though a lot of the spec text is still in very heavy flux, a lot of effort has been put into Section 1 to ensure it captures what we're setting out to solve in this working group/specification. Please read it, and if there's anything you disagree with or feel is missing, please raise an issue!

- assignee(s): Everyone (champion @michaelstaib)
- source: https://github.com/graphql/composite-schemas-wg/blob/main/notes/2024/2024-02.md

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by smyrick** [comment]
For everyone, here is the link: https://github.com/graphql/composite-schemas-spec/blob/main/spec/Section%201%20--%20Overview.md

Spec docs are over the separate repo: https://github.com/graphql/composite-schemas-spec

**Comment by bignimbus** [comment]
Section 1 LGTM as well 👍🏻

**Comment by JohnStarich** [comment]
Section 1 LGTM.

I particularly like the choice of "encourages" rather than "requires" in the Composable section. That will be key for folks to grow their source graphs' complexity gradually. In other words, it'd be more likely a single source schema is composable from day 1.
