### ISSUE TITLE
Meeting missing from Google Calendar

### ISSUE THREAD

**Issue by jemgillam** [graphql/composite-schemas-wg#19]
The meeting for the composite schema working group needs adding to the [Foundation's Google calendar](https://calendar.google.com/calendar/u/0/embed?src=linuxfoundation.org_ik79t9uuj2p32i3r203dgv5mo8@group.calendar.google.com) (linked from the agenda)

Please say if there's a way for us lurkers to do this in the future.

**Comment by ShogunPanda** [comment]
I second this.
When is the next meeting for this WG happening? 
According to the schedule in the index, it should be Aug 11th, 15:00 UTC.
Am I right? If that's the case, can you please link the Zoom link here?

**Comment by benjie** [comment]
Next 3 meetings are scheduled: https://github.com/graphql/composite-schemas-wg/pull/40

Google Calendar still needs fixing, I met with someone at the Foundation yesterday about that so hopefully we can get that sorted soon.

**Comment by benjie** [comment]
The next meeting is in the calendar.
