### ISSUE TITLE
[2022-08-17] Split glossary into 3 files and add to rfcs folder

### ISSUE THREAD

**Issue by benjie** [graphql/composite-schemas-wg#70]
> split existing document up into 3 parts:
> - Glossary.md (generic terms)
> - VendorSolutions.md (the solutions that are out there)
> - TermsToAvoid.md (branded/misleading/ambiguous terms)

- assignee(s): @n1ru4l 
- source: https://github.com/graphql/composite-schemas-wg/blob/main/notes/2022/2022-08-17.md#next-steps-for-subschema-composability-rules-15m-uri:~:text=To%20split%20existing,misleading/ambiguous%20terms)

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
@n1ru4l Please reply so I can assign you

**Comment by obi1kenobi** [comment]
Adding a note before we all forget: let's make sure to add *client* and *server* to the `TermsToAvoid.md` file, since they are loaded terms that can prevent us from exploring parts of the solution space.
